name: Recurrent Job

on:
  workflow_dispatch: null
  push: null
  schedule:
    - cron: '*/25 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MAILER_AUTH: ${{ secrets.MAILER_AUTH }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
      - run: pnpm ci
      - run: pnpm start
